name: 'Shellcheck Problem Matchers'
description: 'Automatically show shellcheck output as annotations in GitHub'
branding:
  icon: list
  color: purple
inputs:
  format:
    description: 'Specify a specific format. Available options are "gcc" or "tty"'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
